pool:
  vmImage: ubuntu-latest

stages:
- stage: cd
  displayName: Continious Deployment
  jobs:
  - job: docker_build
    displayName: Build and push docker image to ACR
    steps:
    - task: Docker@2
      displayName: Build docker image
      inputs:
        containerRegistry: 'nkatsacr_conn'
        repository: 'dotnetwebapp'
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
    - task: Docker@2
      displayName: Push docker image
      inputs:
        containerRegistry: 'nkatsacr_conn'
        repository: 'dotnetwebapp'
        command: 'push'
        tags: |
          $(Build.BuildId)
          latest