pool:
  vmImage: ubuntu-latest

stages:
- stage: cd
  displayName: Continious Deployment
  jobs:
  - job: docker_build
    displayName: Build docker image
    steps:
    - task: Docker@2
      inputs:
        repository: 'dotnetwebapp'
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest